### PR TITLE
Added issue and PR template

### PR DESCRIPTION
**Pull request by tripathyprateek**
Signed-off-by: tripathyprateek <tripathy.prateek@gmail.com>

### CODE REVIEW

**Review by t0xic0der — CHANGES_REQUESTED** [review]
Please target your PR from a non-master branch of your fork to the [`fomantic-and-asciidocs`](https://github.com/t0xic0der/syngrafias/tree/fomantic-and-asciidocs) branch of the original repository.

**Comment by tripathyprateek** [comment]
Issue template and PR template work only in master branch that's why I sent this directly to master. The .github doesn't need to be in any other branch and would still work correctly.

**Comment by t0xic0der** [comment]
Re: https://github.com/t0xic0der/syngrafias/pull/55#issuecomment-730186829

That is true. Do target your PR from a non-master branch of your fork to the master of the original.

**Comment by t0xic0der** [comment]
@s-katte Could you please review this please?

**Comment by s-katte** [comment]
> @s-katte Could you please review this please?

sure

**Review by s-katte — CHANGES_REQUESTED** [review]
Changes requested are:

- Feature request may not have ```Current Behavior``` and ```Desired Behavior``` titles, instead add a title asking a question that confirms the user has scanned through all issues and check for a duplicate if present

- Add a title called ```Pitch```  in feature request that helps contributors and maintainers to convinces why and how the feature would be useful for the project.

- Add another issue template for documentation.

- In PR template, add a title for ```Screenshots (if applicable)``` and the title for confirming that contributor has read the ```CONTRIBUTING.md``` to ensure the standards.

**Comment by t0xic0der** [comment]
Any updates on this @tripathyprateek?

**Review by s-katte — APPROVED** [review]
Looks good to me.
@VaibhavSaini19 have a look.

**Review by VaibhavSaini19 — APPROVED** [review]
Looks good

**Review by t0xic0der — APPROVED** [review]
Conforming with the +1s of @VaibhavSaini19 and @s-katte. Merging this PR.

**Pull request merged**
