### PR TITLE
Rolled back nuisance theming for cell blocks

### PR DESCRIPTION
**Pull request by t0xic0der**
Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>

**Description**
This PR fixes "your eyes".

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Yep.

**Notes for Reviewers**
(TO BE ADDED)

**Screenshot for changes made**
image

**Thank you for contributing to Syngrafias!**
Hmm.

### CODE REVIEW

**Comment by t0xic0der** [comment]
Hi @shivangswain @VaibhavSaini19 @s-katte @khallnayak, please go ahead and review this PR.

**Review by VaibhavSaini19 — COMMENTED** [review]
Looks better now. But wasn't the background an even lighter shade earlier before theming?

**Comment by t0xic0der** [comment]
> Looks better now. But wasn't the background an even lighter shade earlier before theming?

It was entirely white. Should I make the changes happen?

**Comment by VaibhavSaini19** [comment]
> It was entirely white. Should I make the changes happen?
Either make it white, or a lighter shade (maybe something like #F6F8FA)

**Comment by t0xic0der** [comment]
Changed the colour to the requested one.

image

**Review by VaibhavSaini19 — APPROVED** [review]
Looks much cleaner

**Pull request merged**
