### PR TITLE
Full height editor

### LINKED ISSUE #50: The textbox is expected to occupy the entire height
image

### PR DESCRIPTION
**Pull request by s-katte**
---

**Description**

This PR fixes #50 

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Yes

---
**Screenshot for changes made**<p>&nbsp;</p>
image

### CODE REVIEW

**Comment by t0xic0der** [comment]
@tripathyprateek - Kindly provide reviews

**Review by t0xic0der — CHANGES_REQUESTED** [review]
The font size and the positional designs of the login page do not look the same as the default one.

This is how it should look.
image

And this is how it currently looks.
image

Please restore the login as the default.

**Comment by t0xic0der** [comment]
Appreciate the works done regarding already placing the scrollbar in both the text and the preview view.

Good work @VaibhavSaini19 and @s-katte!

image

**Comment by t0xic0der** [comment]
Hi @tripathyprateek @shivangswain @VaibhavSaini19! Could you assist with reviewing this PR?

Also, @s-katte please make sure that the branch of your fork is synchronized with the upstream reference branch. This would help you get rid of the branch conflict issues.

**Comment by s-katte** [comment]
> Also, @s-katte please make sure that the branch of your fork is synchronized with the upstream reference branch. This would help you get rid of the branch conflict issues.

sure, will do it from next time

**Comment by t0xic0der** [comment]
Take a look at @VaibhavSaini19's changes. At fca28b0, he first merges the changes that may have happened in the upstream before going ahead to introduce his own changes. 

image

That is one of the most recommended ways of keeping the said branch of your fork up-to-date to the changes made in the upstream.

**Comment by s-katte** [comment]
Done all the required changes

## Here is a screenshot

image

**Review by t0xic0der — CHANGES_REQUESTED** [review]
The padding needs some work for the preview mode.

image

Also, rename the "Singular document" to "ADOC Unity Mode (Unstable)" so that we can facilitate a merge.

**Comment by t0xic0der** [comment]
I know that this PR is a WIP but please do add padding in the preview field.

image

**Comment by t0xic0der** [comment]
## Things to do
- Synchronize document name
- Notify users when content editing takes place
- Notify users when document title is edited
- Save documents to local disk storage
- Open documents from local disk storage
- Add theming option in the Unity Mode
- Rename "Singular document" to "Unity Mode (Markdown)"
- Track activities and changes made in the document and title
- Activate the "Reset workspace" button
- Remove the "Append cell" button from the "Unity Mode (Markdown)"

**Comment by t0xic0der** [comment]
This branch of your fork would be subjected to PRs from https://github.com/astrosonic/fork-of-s-katte-syngrafias/tree/full-height-editor. Make sure to review and merge them to your location first before merging them here.

**Comment by t0xic0der** [comment]
Works well for me except for the error that I am getting in the console.

image

**Comment by t0xic0der** [comment]
Also, add the eye icon which toggles 100% of each preview or 50-50% of both.

**Review by t0xic0der — APPROVED** [review]
Looks good to me.

@shivangswain @tripathyprateek @VaibhavSaini Please review.

**Review by shivangswain — APPROVED** [review]
Works good. GG.

**Review by VaibhavSaini19 — APPROVED** [review]
Looks good to me

**Comment by t0xic0der** [comment]
Three approvals. Merging now.

**Pull request merged**
