### PR TITLE
Added help and support topics

### LINKED ISSUE #74: Introduce a full-blown wiki inside of the web application
**Check Duplicate issue**
This issue has not been mentioned of before.

**Pitch your idea/new feature to add**
The web application should contain the documentation in itself explaining how to make things work in Syngrafias, while explaining the nuances and terminologies that are being used. Also the random tips should all be listed in one of the sections of the documentation to ensure that all the tips are visible to the user on demand. Inclusion of screenshots wherever necessary would also be appreciated.

**Alternatives**
Including the wiki inside the web application might make it heavier and clumsier in terms of code management and maintainability. The use of JAMstack using a static site generator for generating the frontend for the documentation can be suggested here. The likes of MkDocs, Hugo, GitBook etc are good alternatives here.

### PR DESCRIPTION
**Pull request by t0xic0der**
Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>

**Description**

This PR fixes #74

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Yes.

**Screenshot for changes made**
image
image

The top artefact would be resolved with the new UI automatically.

### CODE REVIEW

**Comment by t0xic0der** [comment]
@shivangswain @VaibhavSaini19 @tripathyprateek @s-katte Please review.

**Comment by t0xic0der** [comment]
image

**Review by VaibhavSaini19 — APPROVED** [review]
LGTM

**Review by shivangswain — APPROVED** [review]
Everything is functional. Approved.

**Review by s-katte — APPROVED** [review]
Looks good

**Pull request merged**
