### PR TITLE
Variable cell partition width

### LINKED ISSUE #59: Add slider to modify partition width of cell
## 🚀 Feature

Add a slider in between the cell's code area and preview partition to enable the user to modify their width as desired

## Have you spent some time to check if this issue has been raised before?

Yes, similar issue doesn't exist

### Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This would enhance the user experience greatly

### PR DESCRIPTION
**Pull request by VaibhavSaini19**
---

**Description**

This PR fixes #59 

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**

Yes

**Notes for Reviewers**

Since Split.js modifies the width of the cell partition, I had to remove the `ui grid` , `eight column wide` and `sixteen column wide` classes and use `display: flex`. 

P.S. Isn't the textarea supposed to occupy the full height? It has been given 2 rows height by default

---
**Screenshot for changes made**<p>&nbsp;</p>

Screenshot (187)

### CODE REVIEW

**Comment by t0xic0der** [comment]
Hi @shivangswain @VaibhavSaini19 @s-katte @khallnayak, please go ahead and review this PR.

> Since Split.js modifies the width of the cell partition, I had to remove the ui grid , eight column wide and sixteen column wide classes and use display: flex.

Which basically undoes the consequences of #58, right?

> P.S. Isn't the textarea supposed to occupy the full height? It has been given 2 rows height by default

Yes it is supposed to. Please make the necessary changes to accompany those as well.

**Comment by VaibhavSaini19** [comment]
> Which basically undoes the consequences of #58, right?

I already made the necessary changes to maintain the desired functionality. It switches between 50-50 width, 100% width to textarea cell and 100% width to output cell. It is just that it won't remember your manual width partition if you cycle toggle

> Yes it is supposed to. Please make the necessary changes to accompany those as well.

Should I make a new issue regarding that, since it is a problem on its own, unrelated to this PR?

**Comment by t0xic0der** [comment]
> It is just that it won't remember your manual width partition if you cycle toggle

Not a problem. It is something we can live with.

> Should I make a new issue regarding that, since it is a problem on its own, unrelated to this PR?

Please go ahead and create an issue regarding the same. Remember that the issue would garner prevalence only when #71 is merged.

**Comment by t0xic0der** [comment]
Hi @shivangswain @s-katte @tripathyprateek, I could use your reviews here. Thank you.

**Review by s-katte — APPROVED** [review]
Looks good to me.

**Review by t0xic0der — CHANGES_REQUESTED** [review]
Hate to be the one to break this to you but the toggle functionality does not work anymore.

image

**Comment by VaibhavSaini19** [comment]
@t0xic0der its working fine on my end. @s-katte can you confirm if it is working as expected?

**Review by t0xic0der — APPROVED** [review]
LGTM at my end as well. Just had to hard refresh to load some JS assets.

**Comment by shivangswain** [comment]
Works great for me too.

**Pull request merged**
