### PR TITLE
Quick reference for AsciiDoc and Modified URL patterns

### PR DESCRIPTION
**Pull request by t0xic0der**
**Description**
This PR addresses issues mentioned in https://lists.fedorahosted.org/archives/list/devel@lists.fedoraproject.org/message/CXXZ6YIL22Y34SIFT6XWK3DL3FD5VCLF/ and https://lists.fedorahosted.org/archives/list/devel@lists.fedoraproject.org/message/ZWSKCQ2BQD4UZJAKEDNREF3FX6RVCDAR/.

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Yes.

**Screenshot for changes made**
Screenshot_2021-01-04 Syngrafias
Screenshot_2021-01-04 Unity Mode ADOC
Screenshot from 2021-01-04 11-42-39

### CODE REVIEW

**Comment by t0xic0der** [comment]
Please review @nasirhm @shivangswain @VaibhavSaini19 @s-katte.

**Review by VaibhavSaini19 — APPROVED** [review]
Looks great to me

**Review by nasirhm — APPROVED** [review]
LGTM

**Comment by t0xic0der** [comment]
Thanks for your reviews. @nasirhm @VaibhavSaini19

Merging.

**Comment by t0xic0der** [comment]
Pulled the changes in the instance.

image

**Pull request merged**
