### PR TITLE
Save documents to client's local storage

### LINKED ISSUE #60: Build documentation saving functionality for the remake
## 🚀 Feature

Add buttons to allow the user to open / save a document 

## Have you spent some time to check if this issue has been raised before?

Yes, similar issue doesn't exist

### Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

Currently, there is no option to save document in the remake branch

### PR DESCRIPTION
**Pull request by t0xic0der**
**Description**
This PR fixes #60.

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Yep.

**Notes for Reviewers**
(TO BE ADDED)

**Screenshot for changes made**
```
{
	"username": "t0xic0der",
	"sessiden": "DEADCAFE",
	"timestmp": 1607621794116,
	"cellcoll": {
		"37AC8414": {
			"metadata": {
				"cellauth": "t0xic0der",
				"maketime": 1607621709692
			}, 
			"contents": {
				"cellname": "Hello",
				"textdata": "== Hi\n\nHow are you?"
			}
		},
		"77C81049": {
			"metadata": {
				"cellauth": "t0xic0der",
				"maketime": 1607621744197
			},
			"contents": {
				"cellname": "Ta ta",
				"textdata": "== Bye-bye\n\nNice meeting you."
			}
		}
	}
}
```

Screenshot from 2020-12-10 23-09-12

Screenshot_2020-12-10 Syngrafias(2)

Screenshot_2020-12-10 Syngrafias(1)

Screenshot_2020-12-10 Syngrafias

**Thank you for contributing to Syngrafias!**
Hmm.

### CODE REVIEW

**Comment by t0xic0der** [comment]
Hi @shivangswain @VaibhavSaini19 @s-katte @khallnayak, please go ahead and review this PR.

**Review by VaibhavSaini19 — APPROVED** [review]
Looks good to me

**Review by s-katte — CHANGES_REQUESTED** [review]
The functionality works well for me, just mention while saving the file, in the modal that the file will be saved with a hashed timestamp appended.

**Comment by t0xic0der** [comment]
> The functionality works well for me, just mention while saving the file, in the modal that the file will be saved with a hashed timestamp appended.

This is supposed to stay that way for the scope of this PR. Changing that would be a new issue which I would make shortly.

**Review by shivangswain — APPROVED** [review]
It just works. Amazing!

**Pull request merged**
