### PR TITLE
Open documents from local storage

### LINKED ISSUE #62: Build documentation opening functionality for the remake
## 🚀 Feature

Add buttons to allow the user to open / save a document 

## Have you spent some time to check if this issue has been raised before?

Yes, similar issue doesn't exist

### Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

Currently, there is no option to open document in the remake branch

### PR DESCRIPTION
**Pull request by t0xic0der**
**Description**
This PR fixes #62.

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Hmm.

**Notes for Reviewers**
(TO BE ADDED)

**Screenshot for changes made**
Screenshot_2020-12-11 Syngrafias
Screenshot_2020-12-11 Syngrafias(1)
Screenshot_2020-12-11 Syngrafias(2)
Screenshot from 2020-12-10 23-09-12

**Thank you for contributing to Syngrafias!**
Hmm.

### CODE REVIEW

**Comment by t0xic0der** [comment]
Hi @shivangswain @VaibhavSaini19 @s-katte @khallnayak, please go ahead and review this PR.

**Review by s-katte — CHANGES_REQUESTED** [review]
The functionality works well for me, just change epochs to time after opening the document.

**Review by VaibhavSaini19 — APPROVED** [review]
Looks good to me

**Comment by t0xic0der** [comment]
Converted epoch time display to localtime

image

**Comment by t0xic0der** [comment]
@shivangswain Please review.

**Review by shivangswain — APPROVED** [review]
Review done. Works fine.

**Pull request merged**
