### PR TITLE
Added special read-only cards

### PR DESCRIPTION
**Pull request by t0xic0der**
**Description**
This PR fixes https://github.com/t0xic0der/syngrafias/issues/9.

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Yep.

**Notes for Reviewers**
(TO BE ADDED)

**Screenshot for changes made**
image
image
image
image
image

**Thank you for contributing to Syngrafias!**
Hmm.

### CODE REVIEW

**Comment by t0xic0der** [comment]
Hi @shivangswain @VaibhavSaini19 @s-katte @khallnayak, please go ahead and review this PR.

**Review by s-katte — CHANGES_REQUESTED** [review]
The functionality works just fine for me, just a few changes requested:
- [ ] use ```title``` or ```tooltip``` to show that the lock button is for making the cell read-only.
- [ ] rollback all unnecessary changes made in both files like adding new lines.

**Comment by t0xic0der** [comment]
> use `title` or `tooltip` to show that the lock button is for making the cell read-only.

Got it. Will do it rightaway.

> rollback all unnecessary changes made in both files like adding new lines.

I am not sure if we should do that. I am attempting to make the character-per-line to fall under 160 to make it compliant to most modern code quality checks.

**Comment by s-katte** [comment]
> I am not sure if we should do that. I am attempting to make the character-per-line to fall under 160 to make it compliant to most modern code quality checks.

I would suggest you do it to follow atomic PRs consistently which will help everyone one to look exact, required and appropriate changes made for the respective title.

You can make a new issue for this if it is not already listed.

**Review by VaibhavSaini19 — CHANGES_REQUESTED** [review]
Works great. 
Just a suggestion to change the `delete cell` button's icon to trashcan, as it makes it more intuitive that it is a delete button.

**Comment by t0xic0der** [comment]
Now the buttons look like this. 

image

image

image

image

**Review by VaibhavSaini19 — APPROVED** [review]
Looks good to me

**Review by shivangswain — APPROVED** [review]
Works good on my end.

**Pull request merged**
