### PR TITLE
Stuck the menu bar to the top

### PR DESCRIPTION
**Pull request by shivangswain**
Resolves: #56

### CODE REVIEW

**Review by VaibhavSaini19 — CHANGES_REQUESTED** [review]
Behaves as expected as long as the cells don't exceed the initial height of the viewport. After adding more than around 8 cells on desktop, if you scroll down more than the initial body height, the menu bar is left behind, since the body height (100%) is calculated when the page is loaded, and position stick sticks to only that height. Add overflow: auto to the body to fix this

**Comment by t0xic0der** [comment]
Any updates @shivangswain on the changes suggested by @VaibhavSaini19?

**Comment by shivangswain** [comment]
The solution provided by Vaibhav didn't work for me but I fixed it in my own way

**Review by t0xic0der — APPROVED** [review]
Works just as good as expected. :+1:

**Pull request merged**
