### PR TITLE
Textarea occupies the same height as preview section

### LINKED ISSUE #79: Textarea doesn't occupy parent's full height
**Description**

The textarea in the `fomantic and asciidoc` branch does not occupy the full height of its parent container as its row size is given 2.

**Expected Behavior**

Textarea size increases automatically to fill parent container height

**Screenshot**<p>&nbsp;</p>

Screenshot (187)

**Enviroment:**
- Host OS: Windows 10
- Browser: Chrome Version 86.0.4240.198

**To Reproduce**
1. Open a Syngrafias document
2. Add a new cell, if doesn't exist
3. Type or paste some large text content in the input textarea

---
[Optional] **Additional Context**

This issue should be fixed only after #71 is merged

### PR DESCRIPTION
**Pull request by VaibhavSaini19**
---

**Description**

This PR fixes #79 

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**<p>&nbsp;</p>
Yes

**Notes for Reviewers**<p>&nbsp;</p>
To be merged only after #71 
---
**Screenshot for changes made**<p>&nbsp;</p>
Screenshot (188)

### CODE REVIEW

**Review by s-katte — APPROVED** [review]
Looks and works well for me.

**Review by t0xic0der — CHANGES_REQUESTED** [review]
The toggle functionality is broken here as well.

image

To be merged after #71 is merged.

**Comment by VaibhavSaini19** [comment]
@t0xic0der its working fine in this as well on my end

**Comment by t0xic0der** [comment]
Could you confirm the same on Firefox?

**Comment by VaibhavSaini19** [comment]
Yes, it is working fine on Firefox as well

Screenshot (192)

**Comment by t0xic0der** [comment]
I think it must be a case with hard-refreshing to load the newly changed JavaScript assets.

**Review by t0xic0der — APPROVED** [review]
LGTM. Approving.

**Comment by t0xic0der** [comment]
@VaibhavSaini19 Please go ahead and resolve the conflicts.

@shivangswain would shortly provide a review and after your conflicts are resolved, I will merge this thing.

**Comment by shivangswain** [comment]
Works good. Just resolving the conflicts remains.

**Pull request merged**
