### PR TITLE
Rewrote cell DOM creation with template literals

### PR DESCRIPTION
**Pull request by t0xic0der**
Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>

**Description**
This PR is a functional rewrite of cell DOM creation using template literals.

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Yes

**Screenshot for changes made**
template-literals

### CODE REVIEW

**Comment by t0xic0der** [comment]
@VaibhavSaini19 @shivangswain @s-katte @tripathyprateek Please review.

**Review by shivangswain — APPROVED** [review]
Works on my end. Good job.

**Review by VaibhavSaini19 — CHANGES_REQUESTED** [review]
If you could use the same format of template literals everywhere else as well, it would be great

**Comment by t0xic0der** [comment]
Done. Please check.

**Review by VaibhavSaini19 — APPROVED** [review]
LGTM

**Comment by tripathyprateek** [comment]
Looks good to me!

**Review by tripathyprateek — APPROVED** [review]

**Comment by t0xic0der** [comment]
Thanks for reviewing these changes @tripathyprateek @VaibhavSaini19 @shivangswain!

**Pull request merged**
